import { HttpStatus } from '@nestjs/common';

export const DOMAIN_ERROR_HTTP_MAP: Record<string, HttpStatus> = {
  ENTRY_NOT_FOUND: HttpStatus.NOT_FOUND,
  ENTRY_EMPTY: HttpStatus.UNPROCESSABLE_ENTITY,
  ENTRY_ALREADY_VALIDATED: HttpStatus.CONFLICT,

  PRODUCT_NOT_FOUND: HttpStatus.NOT_FOUND,
  PRODUCT_ALREADY_EXISTS: HttpStatus.CONFLICT,
  PRODUCT_ARCHIVED: HttpStatus.CONFLICT,

  INVALID_WEIGHT: HttpStatus.BAD_REQUEST,

  INVALID_CREDENTIALS: HttpStatus.UNAUTHORIZED,
  NO_ACTIVE_CENTER: HttpStatus.FORBIDDEN,

  PERSISTENCE_ERROR: HttpStatus.INTERNAL_SERVER_ERROR,
};
